title: Harsh Bharat Kakashaniya
tagline: "Think like a proton. Always positive."
version:
permalink: /:categories/:title/
baseurl: ""
repository:
  web: "harshkakashaniya.github.io"
  git: "git:////github.com/harshkakashaniya/harshkakashaniya.github.io"
google:
  search: ""
  analytics: ""
  plus: ""
highlight_libraries:
  - noflo-couchdb
  - noflo-diffbot
  - noflo-ducksboard
  - noflo-github
  - noflo-stripe
  - noflo-redis
  - noflo-twilio
  - noflo-twitter
exclude:
  - "node_modules"
  - "Gruntfile.coffee"
  - "README.md"
  - "npm-debug.log"
  - "package.json"
  - "docco.css"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
