title: Harsh Bharat Kakashaniya
tagline: "Think like a proton. Always positive."
version:
permalink: /:categories/:title/
baseurl: ""
repository:
  web: "harshkakashaniya.github.io"
  git: "git:////github.com/harshkakashaniya/harshkakashaniya.github.io"
google:
  search: ""
  analytics: ""
  plus: ""
highlight_libraries:
  - comp_1
  - comp_2
  - comp_3
  - comp_4
  - comp_5
  - comp_6
  - comp_7
  - comp_8
exclude:
  - "Gruntfile.coffee"
  - "README.md"
  - "package.json"
